package fhirconverter.spark;

import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.parser.DataFormatException;
import ca.uhn.fhir.parser.IParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.fge.jsonpatch.JsonPatch;
import com.github.fge.jsonpatch.diff.JsonDiff;
import org.hl7.fhir.dstu3.model.Patient;
import org.hl7.fhir.instance.model.api.IBaseResource;
import org.json.JSONObject;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;

public class FHIRParserTest {

    private final String XML_PATIENT = "<Patient xmlns=\"http://hl7.org/fhir\">\n" +
            "    <id value=\"170445\"/>\n" +
            "    <meta>\n" +
            "        <versionId value=\"1\"/>\n" +
            "        <lastUpdated value=\"2017-07-06T13:12:42.328-04:00\"/>\n" +
            "        <profile value=\"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-PersonOfRecord\"/>\n" +
            "    </meta>\n" +
            "    <text>\n" +
            "        <status value=\"generated\"/>\n" +
            "        <div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by \n" +
            "         \n" +
            "            <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>. Version identifier: b38b8877256db0b7ec1ede270729a1c940ad8b33\n" +
            "        </div>\n" +
            "    </text>\n" +
            "    <extension url=\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-race\">\n" +
            "        <valueCodeableConcept>\n" +
            "            <coding>\n" +
            "                <system value=\"http://hl7.org/fhir/v3/Race\"/>\n" +
            "                <code value=\"2106-3\"/>\n" +
            "                <display value=\"White\"/>\n" +
            "            </coding>\n" +
            "            <text value=\"race\"/>\n" +
            "        </valueCodeableConcept>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity\">\n" +
            "        <valueCodeableConcept>\n" +
            "            <coding>\n" +
            "                <system value=\"http://hl7.org/fhir/v3/Ethnicity\"/>\n" +
            "                <code value=\"2186-5\"/>\n" +
            "                <display value=\"Nonhispanic\"/>\n" +
            "            </coding>\n" +
            "            <text value=\"ethnicity\"/>\n" +
            "        </valueCodeableConcept>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://hl7.org/fhir/StructureDefinition/birthPlace\">\n" +
            "        <valueAddress>\n" +
            "            <city value=\"Fitchburg\"/>\n" +
            "            <state value=\"MA\"/>\n" +
            "            <country value=\"US\"/>\n" +
            "        </valueAddress>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName\">\n" +
            "        <valueString value=\"Juliet345 Pollich990\"/>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex\">\n" +
            "        <valueCode value=\"F\"/>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://hl7.org/fhir/StructureDefinition/patient-interpreterRequired\">\n" +
            "        <valueBoolean value=\"false\"/>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://standardhealthrecord.org/fhir/StructureDefinition/shr-actor-FictionalPerson-extension\">\n" +
            "        <valueBoolean value=\"true\"/>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-FathersName-extension\">\n" +
            "        <valueHumanName>\n" +
            "            <text value=\"Dane156 Stroman117\"/>\n" +
            "        </valueHumanName>\n" +
            "    </extension>\n" +
            "    <extension url=\"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-SocialSecurityNumber-extension\">\n" +
            "        <valueString value=\"999-27-8612\"/>\n" +
            "    </extension>\n" +
            "    <identifier>\n" +
            "        <system value=\"https://github.com/synthetichealth/synthea\"/>\n" +
            "        <value value=\"1b837734-5083-4590-b588-4c7732e5ac8f\"/>\n" +
            "    </identifier>\n" +
            "    <identifier>\n" +
            "        <type>\n" +
            "            <coding>\n" +
            "                <system value=\"http://hl7.org/fhir/identifier-type\"/>\n" +
            "                <code value=\"SB\"/>\n" +
            "            </coding>\n" +
            "        </type>\n" +
            "        <system value=\"http://hl7.org/fhir/sid/us-ssn\"/>\n" +
            "        <value value=\"999278612\"/>\n" +
            "    </identifier>\n" +
            "    <identifier>\n" +
            "        <type>\n" +
            "            <coding>\n" +
            "                <system value=\"http://hl7.org/fhir/v2/0203\"/>\n" +
            "                <code value=\"DL\"/>\n" +
            "            </coding>\n" +
            "        </type>\n" +
            "        <system value=\"urn:oid:2.16.840.1.113883.4.3.25\"/>\n" +
            "        <value value=\"S99969306\"/>\n" +
            "    </identifier>\n" +
            "    <identifier>\n" +
            "        <type>\n" +
            "            <coding>\n" +
            "                <system value=\"http://hl7.org/fhir/v2/0203\"/>\n" +
            "                <code value=\"PPN\"/>\n" +
            "            </coding>\n" +
            "        </type>\n" +
            "        <system value=\"http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber\"/>\n" +
            "        <value value=\"X77003736X\"/>\n" +
            "    </identifier>\n" +
            "    <identifier>\n" +
            "        <type>\n" +
            "            <coding>\n" +
            "                <system value=\"http://hl7.org/fhir/v2/0203\"/>\n" +
            "                <code value=\"MR\"/>\n" +
            "            </coding>\n" +
            "        </type>\n" +
            "        <system value=\"http://hospital.smarthealthit.org\"/>\n" +
            "        <value value=\"1b837734-5083-4590-b588-4c7732e5ac8f\"/>\n" +
            "    </identifier>\n" +
            "    <name>\n" +
            "        <use value=\"official\"/>\n" +
            "        <family value=\"Hansen448\"/>\n" +
            "        <given value=\"Elissa46\"/>\n" +
            "        <prefix value=\"Mrs.\"/>\n" +
            "    </name>\n" +
            "    <name>\n" +
            "        <use value=\"maiden\"/>\n" +
            "        <family value=\"Stroman117\"/>\n" +
            "        <given value=\"Elissa46\"/>\n" +
            "    </name>\n" +
            "    <telecom>\n" +
            "        <system value=\"phone\"/>\n" +
            "        <value value=\"(448) 739-2195\"/>\n" +
            "        <use value=\"home\"/>\n" +
            "    </telecom>\n" +
            "    <gender value=\"female\"/>\n" +
            "    <birthDate value=\"1956-04-22\"/>\n" +
            "    <deceasedDateTime value=\"2015-01-04T07:06:43-05:00\"/>\n" +
            "    <address>\n" +
            "        <extension url=\"http://hl7.org/fhir/StructureDefinition/geolocation\">\n" +
            "            <extension url=\"latitude\">\n" +
            "                <valueDecimal value=\"42.610683558943805\"/>\n" +
            "            </extension>\n" +
            "            <extension url=\"longitude\">\n" +
            "                <valueDecimal value=\"-71.07136500645896\"/>\n" +
            "            </extension>\n" +
            "        </extension>\n" +
            "        <line value=\"3992 Metz Mountains\"/>\n" +
            "        <city value=\"North Andover\"/>\n" +
            "        <state value=\"MA\"/>\n" +
            "        <postalCode value=\"01845\"/>\n" +
            "        <country value=\"US\"/>\n" +
            "    </address>\n" +
            "    <maritalStatus>\n" +
            "        <coding>\n" +
            "            <system value=\"http://hl7.org/fhir/v3/MaritalStatus\"/>\n" +
            "            <code value=\"M\"/>\n" +
            "        </coding>\n" +
            "        <text value=\"M\"/>\n" +
            "    </maritalStatus>\n" +
            "    <multipleBirthBoolean value=\"false\"/>\n" +
            "    <communication>\n" +
            "        <language>\n" +
            "            <coding>\n" +
            "                <system value=\"http://hl7.org/fhir/ValueSet/languages\"/>\n" +
            "                <code value=\"en-US\"/>\n" +
            "                <display value=\"English (United States)\"/>\n" +
            "            </coding>\n" +
            "        </language>\n" +
            "    </communication>\n" +
            "    <generalPractitioner>\n" +
            "        <reference value=\"Organization/170444\"/>\n" +
            "    </generalPractitioner>\n" +
            "</Patient>";

    private final String JSON_PATIENT = "{\n" +
            "  \"resourceType\": \"Patient\",\n" +
            "  \"id\": \"170445\",\n" +
            "  \"meta\": {\n" +
            "    \"versionId\": \"1\",\n" +
            "    \"lastUpdated\": \"2017-07-06T13:12:42.328-04:00\",\n" +
            "    \"profile\": [\n" +
            "      \"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-PersonOfRecord\"\n" +
            "    ]\n" +
            "  },\n" +
            "  \"text\": {\n" +
            "    \"status\": \"generated\",\n" +
            "    \"div\": \"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">Generated by <a href=\\\"https://github.com/synthetichealth/synthea\\\">Synthea</a>. Version identifier: b38b8877256db0b7ec1ede270729a1c940ad8b33</div>\"\n" +
            "  },\n" +
            "  \"extension\": [\n" +
            "    {\n" +
            "      \"url\": \"http://hl7.org/fhir/us/core/StructureDefinition/us-core-race\",\n" +
            "      \"valueCodeableConcept\": {\n" +
            "        \"coding\": [\n" +
            "          {\n" +
            "            \"system\": \"http://hl7.org/fhir/v3/Race\",\n" +
            "            \"code\": \"2106-3\",\n" +
            "            \"display\": \"White\"\n" +
            "          }\n" +
            "        ],\n" +
            "        \"text\": \"race\"\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity\",\n" +
            "      \"valueCodeableConcept\": {\n" +
            "        \"coding\": [\n" +
            "          {\n" +
            "            \"system\": \"http://hl7.org/fhir/v3/Ethnicity\",\n" +
            "            \"code\": \"2186-5\",\n" +
            "            \"display\": \"Nonhispanic\"\n" +
            "          }\n" +
            "        ],\n" +
            "        \"text\": \"ethnicity\"\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://hl7.org/fhir/StructureDefinition/birthPlace\",\n" +
            "      \"valueAddress\": {\n" +
            "        \"city\": \"Fitchburg\",\n" +
            "        \"state\": \"MA\",\n" +
            "        \"country\": \"US\"\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName\",\n" +
            "      \"valueString\": \"Juliet345 Pollich990\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex\",\n" +
            "      \"valueCode\": \"F\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://hl7.org/fhir/StructureDefinition/patient-interpreterRequired\",\n" +
            "      \"valueBoolean\": false\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://standardhealthrecord.org/fhir/StructureDefinition/shr-actor-FictionalPerson-extension\",\n" +
            "      \"valueBoolean\": true\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-FathersName-extension\",\n" +
            "      \"valueHumanName\": {\n" +
            "        \"text\": \"Dane156 Stroman117\"\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"url\": \"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-SocialSecurityNumber-extension\",\n" +
            "      \"valueString\": \"999-27-8612\"\n" +
            "    }\n" +
            "  ],\n" +
            "  \"identifier\": [\n" +
            "    {\n" +
            "      \"system\": \"https://github.com/synthetichealth/synthea\",\n" +
            "      \"value\": \"1b837734-5083-4590-b588-4c7732e5ac8f\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\": {\n" +
            "        \"coding\": [\n" +
            "          {\n" +
            "            \"system\": \"http://hl7.org/fhir/identifier-type\",\n" +
            "            \"code\": \"SB\"\n" +
            "          }\n" +
            "        ]\n" +
            "      },\n" +
            "      \"system\": \"http://hl7.org/fhir/sid/us-ssn\",\n" +
            "      \"value\": \"999278612\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\": {\n" +
            "        \"coding\": [\n" +
            "          {\n" +
            "            \"system\": \"http://hl7.org/fhir/v2/0203\",\n" +
            "            \"code\": \"DL\"\n" +
            "          }\n" +
            "        ]\n" +
            "      },\n" +
            "      \"system\": \"urn:oid:2.16.840.1.113883.4.3.25\",\n" +
            "      \"value\": \"S99969306\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\": {\n" +
            "        \"coding\": [\n" +
            "          {\n" +
            "            \"system\": \"http://hl7.org/fhir/v2/0203\",\n" +
            "            \"code\": \"PPN\"\n" +
            "          }\n" +
            "        ]\n" +
            "      },\n" +
            "      \"system\": \"http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber\",\n" +
            "      \"value\": \"X77003736X\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\": {\n" +
            "        \"coding\": [\n" +
            "          {\n" +
            "            \"system\": \"http://hl7.org/fhir/v2/0203\",\n" +
            "            \"code\": \"MR\"\n" +
            "          }\n" +
            "        ]\n" +
            "      },\n" +
            "      \"system\": \"http://hospital.smarthealthit.org\",\n" +
            "      \"value\": \"1b837734-5083-4590-b588-4c7732e5ac8f\"\n" +
            "    }\n" +
            "  ],\n" +
            "  \"name\": [\n" +
            "    {\n" +
            "      \"use\": \"official\",\n" +
            "      \"family\": \"Hansen448\",\n" +
            "      \"given\": [\n" +
            "        \"Elissa46\"\n" +
            "      ],\n" +
            "      \"prefix\": [\n" +
            "        \"Mrs.\"\n" +
            "      ]\n" +
            "    },\n" +
            "    {\n" +
            "      \"use\": \"maiden\",\n" +
            "      \"family\": \"Stroman117\",\n" +
            "      \"given\": [\n" +
            "        \"Elissa46\"\n" +
            "      ]\n" +
            "    }\n" +
            "  ],\n" +
            "  \"telecom\": [\n" +
            "    {\n" +
            "      \"system\": \"phone\",\n" +
            "      \"value\": \"(448) 739-2195\",\n" +
            "      \"use\": \"home\"\n" +
            "    }\n" +
            "  ],\n" +
            "  \"gender\": \"female\",\n" +
            "  \"birthDate\": \"1956-04-22\",\n" +
            "  \"deceasedDateTime\": \"2015-01-04T07:06:43-05:00\",\n" +
            "  \"address\": [\n" +
            "    {\n" +
            "      \"extension\": [\n" +
            "        {\n" +
            "          \"url\": \"http://hl7.org/fhir/StructureDefinition/geolocation\",\n" +
            "          \"extension\": [\n" +
            "            {\n" +
            "              \"url\": \"latitude\",\n" +
            "              \"valueDecimal\": 42.610683558943805\n" +
            "            },\n" +
            "            {\n" +
            "              \"url\": \"longitude\",\n" +
            "              \"valueDecimal\": -71.07136500645896\n" +
            "            }\n" +
            "          ]\n" +
            "        }\n" +
            "      ],\n" +
            "      \"line\": [\n" +
            "        \"3992 Metz Mountains\"\n" +
            "      ],\n" +
            "      \"city\": \"North Andover\",\n" +
            "      \"state\": \"MA\",\n" +
            "      \"postalCode\": \"01845\",\n" +
            "      \"country\": \"US\"\n" +
            "    }\n" +
            "  ],\n" +
            "  \"maritalStatus\": {\n" +
            "    \"coding\": [\n" +
            "      {\n" +
            "        \"system\": \"http://hl7.org/fhir/v3/MaritalStatus\",\n" +
            "        \"code\": \"M\"\n" +
            "      }\n" +
            "    ],\n" +
            "    \"text\": \"M\"\n" +
            "  },\n" +
            "  \"multipleBirthBoolean\": false,\n" +
            "  \"communication\": [\n" +
            "    {\n" +
            "      \"language\": {\n" +
            "        \"coding\": [\n" +
            "          {\n" +
            "            \"system\": \"http://hl7.org/fhir/ValueSet/languages\",\n" +
            "            \"code\": \"en-US\",\n" +
            "            \"display\": \"English (United States)\"\n" +
            "          }\n" +
            "        ]\n" +
            "      }\n" +
            "    }\n" +
            "  ],\n" +
            "  \"generalPractitioner\": [\n" +
            "    {\n" +
            "      \"reference\": \"Organization/170444\"\n" +
            "    }\n" +
            "  ]\n" +
            "}";

    private final String JSON_PRACTITIONER = "{\n" +
            "  \"resourceType\": \"Practitioner\",\n" +
            "  \"id\": \"clinFhirrlCYioXfKqXVwJPryzeI0rXh6842\",\n" +
            "  \"meta\": {\n" +
            "    \"versionId\": \"4\",\n" +
            "    \"lastUpdated\": \"2017-07-10T01:57:01.668-04:00\"\n" +
            "  },\n" +
            "  \"language\": \"it-CH\",\n" +
            "  \"identifier\": [\n" +
            "    {\n" +
            "      \"system\": \"http://clinfhir.com/fhir/NamingSystem/practitioner\",\n" +
            "      \"value\": \"rlCYioXfKqXVwJPryzeI0rXh6842\"\n" +
            "    }\n" +
            "  ],\n" +
            "  \"active\": true,\n" +
            "  \"telecom\": [\n" +
            "    {\n" +
            "      \"system\": \"email\",\n" +
            "      \"value\": \"james@intrahealth.com\"\n" +
            "    }\n" +
            "  ],\n" +
            "  \"gender\": \"other\",\n" +
            "  \"birthDate\": \"2017-07-10\"\n" +
            "}";

    private final String JSON_PATCH = "[ { \"op\": \"replace\", \"path\": \"/gender\", \"value\": \"other\" }," +
                                        "{ \"op\": \"add\", \"path\": \"/active\", \"value\": [\"true\"] }," +
                                        "{ \"op\": \"remove\", \"path\": \"/deceasedDateTime\"} ]";

    private FHIRParser<Patient> patient_parser;
    private ObjectMapper mapper;
    private IParser xml_parser;
    private IParser json_parser;

    @Before
    public void setUp(){
        patient_parser = new FHIRParser<>(Patient.class);
        mapper = new ObjectMapper();
        FhirContext ctx = FhirContext.forDstu3();
        xml_parser = ctx.newXmlParser();
        json_parser = ctx.newJsonParser();
    }

    @Test
    public void testParseXMLPatient()
    {
        try {
            //Given
            IBaseResource expected_resource = xml_parser.parseResource(XML_PATIENT);
            String expected_string = json_parser.encodeResourceToString(expected_resource);
            JsonNode expected_node = mapper.readTree(expected_string);

            //When
            JSONObject obtained_object = patient_parser.parseXMLResource(XML_PATIENT);
            String obtained_string = obtained_object.toString();
            JsonNode obtained_node = mapper.readTree(obtained_string);

            //Then
            JsonNode nodes_diff = JsonDiff.asJson(expected_node, obtained_node);
            Assert.assertEquals("Parsing a correct xml to Patient resource failed." + nodes_diff.asText(),0, nodes_diff.size());
        } catch (java.io.IOException e){
            e.printStackTrace();
        }
    }

    @Test
    public void testParseJSONPatient()
    {
        try {
            //Given
            JsonNode expected_node = mapper.readTree(JSON_PATIENT);

            //When
            JSONObject obtained_object = patient_parser.parseJSONResource(JSON_PATIENT);
            String obtained_string = obtained_object.toString();
            JsonNode obtained_node = mapper.readTree(obtained_string);

            //Then
            JsonNode nodes_diff = JsonDiff.asJson(expected_node, obtained_node);
            Assert.assertEquals("Parsing a correct json to Patient resource failed." + nodes_diff.asText(),0, nodes_diff.size());
        } catch (java.io.IOException e){
            e.printStackTrace();
        }
    }

    @Test
    public void testResourceWithInvalidParamKey()
    {
        //When
        try {
            JSONObject patient = new JSONObject(JSON_PATIENT);
            patient.put("INCORRECT_KEY", patient.remove("address"));
            String invalid_key_patient = patient.toString();
            JSONObject obtained_object = patient_parser.parseJSONResource(invalid_key_patient);
            Assert.fail("Expected a DataFormatException when resource provided by request has incorrect key");
        }
        //Then
        catch (DataFormatException e){
            Assert.assertEquals("Unknown element 'INCORRECT_KEY' found during parse", e.getMessage());
        }
    }

    @Test
    public void testResourceWithInvalidParamValue()
    {
        //When
        try {
            JSONObject patient = new JSONObject(JSON_PATIENT);
            patient.put("gender", "INCORRECT_VALUE");
            String invalid_value_patient = patient.toString();
            JSONObject obtained_object = patient_parser.parseJSONResource(invalid_value_patient);
            Assert.fail("Expected a DataFormatException when resource provided by request has incorrect value");
        }
        //Then
        catch (DataFormatException e){
            Assert.assertEquals("Invalid attribute value \"INCORRECT_VALUE\": Unknown AdministrativeGender code 'INCORRECT_VALUE'", e.getMessage());
        }
    }

    @Test
    public void testIncompatibleType()
    {
        //When
        try {
            JSONObject obtained_object = patient_parser.parseJSONResource(JSON_PRACTITIONER);
            Assert.fail("Expected a ClassCastException when request provides a Practitioner resource");
        }
        //Then
        catch (ClassCastException e){
            Assert.assertEquals("Cannot cast org.hl7.fhir.dstu3.model.Practitioner to org.hl7.fhir.dstu3.model.Patient", e.getMessage());
        }
    }

    @Test
    public void testParseJSONPatchPatient(){

        try {
            //Given
            JsonPatch expected_patch = mapper.readValue(JSON_PATCH, JsonPatch.class);
            //When
            JsonPatch obtained_patch = patient_parser.parseJSONPatch(JSON_PATCH);
            //Then
            Assert.assertEquals("Parsing a correct json to Patient Patch failed.", expected_patch.toString(), obtained_patch.toString());
        }
        catch (IOException e){
            Assert.fail("Unexpected IOException");
        }
    }
}
